import 'package:google_mlkit_pose_detection/google_mlkit_pose_detection.dart';

const poseLandmarkNames = <PoseLandmarkType, String>{
  PoseLandmarkType.nose: 'nose',
  PoseLandmarkType.leftEyeInner: 'leftEyeInner',
  PoseLandmarkType.leftEye: 'leftEye',
  PoseLandmarkType.leftEyeOuter: 'leftEyeOuter',
  PoseLandmarkType.rightEyeInner: 'rightEyeInner',
  PoseLandmarkType.rightEye: 'rightEye',
  PoseLandmarkType.rightEyeOuter: 'rightEyeOuter',
  PoseLandmarkType.leftEar: 'leftEar',
  PoseLandmarkType.rightEar: 'rightEar',
  PoseLandmarkType.leftMouth: 'leftMouth',
  PoseLandmarkType.rightMouth: 'rightMouth',
  PoseLandmarkType.leftShoulder: 'leftShoulder',
  PoseLandmarkType.rightShoulder: 'rightShoulder',
  PoseLandmarkType.leftElbow: 'leftElbow',
  PoseLandmarkType.rightElbow: 'rightElbow',
  PoseLandmarkType.leftWrist: 'leftWrist',
  PoseLandmarkType.rightWrist: 'rightWrist',
  PoseLandmarkType.leftPinky: 'leftPinky',
  PoseLandmarkType.rightPinky: 'rightPinky',
  PoseLandmarkType.leftIndex: 'leftIndex',
  PoseLandmarkType.rightIndex: 'rightIndex',
  PoseLandmarkType.leftThumb: 'leftThumb',
  PoseLandmarkType.rightThumb: 'rightThumb',
  PoseLandmarkType.leftHip: 'leftHip',
  PoseLandmarkType.rightHip: 'rightHip',
  PoseLandmarkType.leftKnee: 'leftKnee',
  PoseLandmarkType.rightKnee: 'rightKnee',
  PoseLandmarkType.leftAnkle: 'leftAnkle',
  PoseLandmarkType.rightAnkle: 'rightAnkle',
  PoseLandmarkType.leftHeel: 'leftHeel',
  PoseLandmarkType.rightHeel: 'rightHeel',
  PoseLandmarkType.leftFootIndex: 'leftFootIndex',
  PoseLandmarkType.rightFootIndex: 'rightFootIndex',
};
